version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - ./db/db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 1234:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    links:
      - mysql
  back:
    build:
      context: back
      dockerfile: ./dockerfile
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 3000:3000
  front:
    build:
      context: front
      dockerfile: ./dockerfile
    links:
      - mysql
      - back
    depends_on:
      - back
    ports:
      - 80:3000